/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lihang.lab3_5.interfaces;

import com.lihang.lab3_5.business.ProductDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author lihang
 */
public class ManagementPanel extends javax.swing.JPanel {

    private JPanel belowPanel;
    private ProductDirectory prodDir;

    /**
     * Creates new form AcMngWorkPanel
     */
    public ManagementPanel() {
        initComponents();
    }

    public ManagementPanel(JPanel belowPanel, ProductDirectory proList) {
        initComponents();
        this.belowPanel = belowPanel;
        this.prodDir = proList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();

        manageBtn.setText("Manage Products");
        manageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBtnActionPerformed(evt);
            }
        });

        createBtn.setText("Create Product");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 107, Short.MAX_VALUE)
                .addComponent(createBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageBtn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageBtn)
                    .addComponent(createBtn))
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        CreateProductPanel panel = new CreateProductPanel(belowPanel, prodDir);
        this.belowPanel.add("CreateProductJPanel", panel);
        CardLayout layout = (CardLayout) belowPanel.getLayout();
        layout.next(belowPanel);
    }//GEN-LAST:event_createBtnActionPerformed

    private void manageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBtnActionPerformed
        // TODO add your handling code here:
        ManageProductPanel panel = new ManageProductPanel(belowPanel, prodDir);
        this.belowPanel.add("ManageProductJPanel", panel);
        CardLayout layout = (CardLayout) belowPanel.getLayout();
        layout.next(belowPanel);
    }//GEN-LAST:event_manageBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JButton manageBtn;
    // End of variables declaration//GEN-END:variables
}
